#ifndef __GATING_MEMBRANE_H__
#define __GATING_MEMBRANE_H__

#include <stdint.h>

#define INPUT1_INT_GPIO_PORT		GPIOH
#define INPUT1_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT1_INT_GPIO_PIN			GPIO_Pin_2

#define INPUT2_INT_GPIO_PORT		GPIOH
#define INPUT2_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT2_INT_GPIO_PIN			GPIO_Pin_3

#define INPUT3_INT_GPIO_PORT		GPIOH
#define INPUT3_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT3_INT_GPIO_PIN			GPIO_Pin_4

#define INPUT4_INT_GPIO_PORT		GPIOH
#define INPUT4_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT4_INT_GPIO_PIN			GPIO_Pin_9

#define INPUT5_INT_GPIO_PORT		GPIOH
#define INPUT5_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT5_INT_GPIO_PIN			GPIO_Pin_10

#define INPUT6_INT_GPIO_PORT		GPIOH
#define INPUT6_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT6_INT_GPIO_PIN			GPIO_Pin_11

#define INPUT7_INT_GPIO_PORT		GPIOH
#define INPUT7_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT7_INT_GPIO_PIN			GPIO_Pin_12

#define INPUT8_INT_GPIO_PORT		GPIOH
#define INPUT8_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT8_INT_GPIO_PIN			GPIO_Pin_13

#define INPUT9_INT_GPIO_PORT		GPIOH
#define INPUT9_INT_GPIO_CLK			RCC_AHB1Periph_GPIOH
#define INPUT9_INT_GPIO_PIN			GPIO_Pin_14

#define INPUT10_INT_GPIO_PORT		GPIOH
#define INPUT10_INT_GPIO_CLK		RCC_AHB1Periph_GPIOH
#define INPUT10_INT_GPIO_PIN		GPIO_Pin_15

#define INPUT11_INT_GPIO_PORT		GPIOI
#define INPUT11_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT11_INT_GPIO_PIN		GPIO_Pin_0

#define INPUT12_INT_GPIO_PORT		GPIOI
#define INPUT12_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT12_INT_GPIO_PIN		GPIO_Pin_1

#define INPUT13_INT_GPIO_PORT		GPIOI
#define INPUT13_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT13_INT_GPIO_PIN		GPIO_Pin_2

#define INPUT14_INT_GPIO_PORT		GPIOI
#define INPUT14_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT14_INT_GPIO_PIN		GPIO_Pin_4

#define INPUT15_INT_GPIO_PORT		GPIOI
#define INPUT15_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT15_INT_GPIO_PIN		GPIO_Pin_5

#define INPUT16_INT_GPIO_PORT		GPIOI
#define INPUT16_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT16_INT_GPIO_PIN		GPIO_Pin_6

#define INPUT17_INT_GPIO_PORT		GPIOI
#define INPUT17_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT17_INT_GPIO_PIN		GPIO_Pin_7

#define INPUT18_INT_GPIO_PORT		GPIOI
#define INPUT18_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT18_INT_GPIO_PIN		GPIO_Pin_8

#define INPUT19_INT_GPIO_PORT		GPIOI
#define INPUT19_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT19_INT_GPIO_PIN		GPIO_Pin_9

#define INPUT20_INT_GPIO_PORT		GPIOI
#define INPUT20_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT20_INT_GPIO_PIN		GPIO_Pin_10

#define INPUT21_INT_GPIO_PORT		GPIOI
#define INPUT21_INT_GPIO_CLK		RCC_AHB1Periph_GPIOI
#define INPUT21_INT_GPIO_PIN		GPIO_Pin_11



void Gating_Membrane_Init( void );

void read_all_input_state( uint8_t ** p_out_states );

#endif //__GATING_MEMBRANE_H__
