#ifndef __PIEZOELECTRIC_ELEMENT_H__
#define __PIEZOELECTRIC_ELEMENT_H__

#include <includes.h>

#define PIEZOELECTRIC_ELEMENT_NOFCHANEL							5
#define PIEZOELECTRIC_ELEMENT_ADC_CDR_ADDR 					((uint32_t)ADC3+0x4c);
#define PIEZOELECTRIC_ELEMENT_ADC										ADC3
#define PIEZOELECTRIC_ELEMENT_ADC_CLK								RCC_APB2Periph_ADC3
#define PIEZOELECTRIC_ELEMENT_ADC_GPIO_PORT					GPIOF
#define PIEZOELECTRIC_ELEMENT_ADC_GPIO_CLK					RCC_AHB1Periph_GPIOF



#define PIEZOELECTRIC_ELEMENT1_INT_GPIO_PIN         GPIO_Pin_6
#define PIEZOELECTRIC_ELEMENT1_INT_CHANNEL					ADC_Channel_4

#define PIEZOELECTRIC_ELEMENT2_INT_GPIO_PIN         GPIO_Pin_7
#define PIEZOELECTRIC_ELEMENT2_INT_CHANNEL					ADC_Channel_5

#define PIEZOELECTRIC_ELEMENT3_INT_GPIO_PIN         GPIO_Pin_8
#define PIEZOELECTRIC_ELEMENT3_INT_CHANNEL					ADC_Channel_6

#define PIEZOELECTRIC_ELEMENT4_INT_GPIO_PIN         GPIO_Pin_9
#define PIEZOELECTRIC_ELEMENT4_INT_CHANNEL					ADC_Channel_7

#define PIEZOELECTRIC_ELEMENT5_INT_GPIO_PIN         GPIO_Pin_10
#define PIEZOELECTRIC_ELEMENT5_INT_CHANNEL					ADC_Channel_8

#define PIEZOELECTRIC_ELEMENT_ADC_DMA_CLK						RCC_AHB1Periph_DMA2
#define PIEZOELECTRIC_ELEMENT_ADC_DMA_Channel				DMA_Channel_2
#define PIEZOELECTRIC_ELEMENT_ADC_DMA_STREAM				DMA2_Stream0


extern __IO uint16_t ADC_ConvertedValue[PIEZOELECTRIC_ELEMENT_NOFCHANEL];

void PIEZOELECTRIC_ELEMENT_Init( void );

#endif //__PIEZOELECTRIC_ELEMENT_H__

